export const LIQUOR_CATEGORY_GROUPS = {
  Alcohol: ['Beer','Cider','Whisky','Vodka','Gin','Rum','Brandy & Cognac','Tequila & Mezcal','Cane & Local Spirits','Liqueurs & Cream Liqueurs','Aperitifs & Bitters','Ready to Drink (RTD)','Soju & Specialty Spirits'],
  Wine: ['Red Wine','White Wine','Rosé Wine','Champagne & Sparkling Wine','Fortified Wine & Vermouth','Specialty & Flavoured Wine'],
  'Non-Alcoholic': ['Soft Drinks','Mixers & Tonic','Water','Juice','Energy Drinks','Malt & Non-Alcoholic Drinks','Syrups & Cordials'],
  'Tobacco & Nicotine': ['Cigarettes','Vapes & E-Cigarettes'],
  'Health & Personal Care': ['Condoms'],
  'Other Retail': ['Deposits & Returnables','Snacks','Ice','Gift Packs','Accessories'],
} as const
export const LIQUOR_PARENT_BY_LEAF = Object.fromEntries(Object.entries(LIQUOR_CATEGORY_GROUPS).flatMap(([parent, leaves]) => leaves.map((leaf) => [leaf.toLowerCase(), parent]))) as Record<string, keyof typeof LIQUOR_CATEGORY_GROUPS>
export const LIQUOR_PARENTS = Object.keys(LIQUOR_CATEGORY_GROUPS) as Array<keyof typeof LIQUOR_CATEGORY_GROUPS>
export const canonicalParentFor = (name: string) => LIQUOR_PARENT_BY_LEAF[name.trim().toLowerCase()]
export const canonicalLeafNames = Object.keys(LIQUOR_PARENT_BY_LEAF)

const rules: Array<[RegExp, string]> = [
  [/\bsmirnoff\s+(?:black ice|ele ginseng|guarana|ice pineapple)\b|\bgordon\s+pm\s+(?:dry|pink)\s*&\s*tonic\b/i, 'Ready to Drink (RTD)'],
  [/\bstrawberry icecream\b/i, 'Vapes & E-Cigarettes'],
  [/\bk\s*vant\b/i, 'Gin'],
  [/\bcrazy cock\b/i, 'Whisky'],
  [/\bcaptain gold(?: local)?\b/i, 'Rum'],
  [/\bchrome(?: lemon)?\b/i, 'Vodka'],
  [/\bjust right\b/i, 'Liqueurs & Cream Liqueurs'],
  [/\bkane extra(?: gold)?\b|\bk\.c\.?\s*(?:citrus|pineapple)\b/i, 'Cane & Local Spirits'],
  [/\bv\s*&\s*a\b/i, 'Liqueurs & Cream Liqueurs'],
  [/\bglenmorangie\b/i, 'Whisky'],
  [/\b(?:all\s*seasons|8\s*pm|ac[e]?\s*black|reserve\s*7|top\s*secret)\b/i, 'Whisky'],
  [/\b(?:oj|atlas)\s*\d+\s*%/i, 'Beer'],
  [/\bkibao\s+gin\b/i, 'Gin'],
  [/\bkibao(?:\s+(?:1\/4|1\/2|3\/4|250ml|350ml|750ml))?\b/i, 'Vodka'],
  [/\bcounty\s+(?:250ml|750ml)\b/i, 'Brandy & Cognac'],
  [/\bzappa\s+(?:black|blue|clear|red|green)\b/i, 'Liqueurs & Cream Liqueurs'],
  [/\bsaint anna\b/i, 'White Wine'],
  [/\bst\.?\s*celine\b/i, 'Red Wine'],
  [/\basconi kagor lux\b|\bascon kagor lux\b/i, 'Red Wine'],
  [/\boak cask\b/i, 'Rum'],
  [/\bgeneral meak(?:ins?|ings?)\b/i, 'Cane & Local Spirits'],
  [/\bvat\s*1l\b/i, 'Whisky'],
  [/\bkenya king\b|\bkienyeji\b/i, 'Cane & Local Spirits'],
  [/\blemon punch\b/i, 'Liqueurs & Cream Liqueurs'],
  [/\bwhite house\b/i, 'Whisky'],
  [/\baurose blanc\b/i, 'White Wine'],
  [/jameson|johnnie walker|glenfiddich|glenlivet|chivas|jack daniel|ballantine|famous grouse|teachers|tullamore|talisker|lagavulin|macallan/i, 'Whisky'],
  [/absolut|smirnoff|ciroc|grey goose|flirt vodka|cruz vodka|supreme vodka|redstar vodka/i, 'Vodka'],
  [/tanqueray|gordon.?s|beefeater|bombay sapphire|hendrick|malfy|kibao gin|58 gin/i, 'Gin'],
  [/bacardi|captain morgan|old nick|bumbu|havana club|myers/i, 'Rum'],
  [/hennessy|courvoisier|remy martin|martell|viceroy|richot|napoleon brandy|monarch brandy|musketeer brandy/i, 'Brandy & Cognac'],
  [/don julio|jose cuervo|patron|olmeca|casamigos|clase azul|camino|kah/i, 'Tequila & Mezcal'],
  [/kenya cane|safari cane|konyagi|caribia cane/i, 'Cane & Local Spirits'],
  [/baileys|amarula|kahlua|malibu|sheridans|tia maria|drambuie|blue curacao|cointreau|grand marnier/i, 'Liqueurs & Cream Liqueurs'],
  [/campari|angostura|origin bitters/i, 'Aperitifs & Bitters'],
  [/jinro|soju/i, 'Soju & Specialty Spirits'],
  [/red bull|kabisa|hypno|qb/i, 'Energy Drinks'],
  [/star walker.*whisky|jameson|glenfiddich/i, 'Whisky'],
  [/smirnoff ice|\brtd\b|premix|g\s*&\s*t/i, 'Ready to Drink (RTD)'],
  [/four cousins.*red|\bmerlot\b|\bshiraz\b|cabernet|pinotage|malbec|sweet red/i, 'Red Wine'],
  [/four cousins.*white|sauvignon blanc|chardonnay|chenin blanc|sweet white/i, 'White Wine'],
  [/four cousins.*rose|four cousins.*rosé|sweet rose|crisp rose/i, 'Rosé Wine'],
  [/mo[eë]t|dom perignon|prosecco|belaire|j\.c\.? le roux|\bbrut\b|blanc de blanc|blanc de noir|sparkling/i, 'Champagne & Sparkling Wine'],
  [/del monte|nature.?s fresh|lime juice/i, 'Juice'],
  [/keringet|safari h2o/i, 'Water'],
  [/dunhill|embassy|safari kings|sportsman|sweet menthol/i, 'Cigarettes'],
  [/\bkiss\b|\btrust\b.*(?:classic|ribbed|studded)/i, 'Condoms'],
  [/\b\d{4,5}\s*puffs?\b|vape|e-cigarette|australian ice mango|california strawberry mint|minty snow/i, 'Vapes & E-Cigarettes'],
  [/coke|coca.?cola|soda|lemonade|appy fizz/i, 'Soft Drinks'],
  [/tonic|ginger ale|mixer/i, 'Mixers & Tonic'],
]
export const classifyLiquorProduct = (name: string) => rules.find(([pattern]) => pattern.test(name))?.[1] ?? null
export const NON_PRODUCT_LINE_PATTERN = /car lease expense|dsr prk payoff|fuel expense|quarterly incentive|rent/i
