allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  prisma: false
  sharp: true
  unrs-resolver: false

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver

overrides:
  nanostores: 1.3.0
