'use client'

import Link from 'next/link'
import { Clock3, ReceiptText, ShoppingCart, Users } from 'lucide-react'

export function CashierHome({ name, branchName, activeClockIn }: { name: string; branchName: string; activeClockIn: string | null }) {
  const time = activeClockIn ? new Intl.DateTimeFormat('en-KE', { hour: 'numeric', minute: '2-digit' }).format(new Date(activeClockIn)) : null
  return <main className="mx-auto max-w-6xl space-y-6 pb-10"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-semibold text-[#c91f21]">CASHIER HOME</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Welcome back, {name.split(' ')[0]}</h1><p className="mt-2 text-sm text-slate-600">{branchName} · Start your shift, serve customers, and keep your register moving.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/dashboard/pos" className="inline-flex h-11 items-center gap-2 rounded-lg bg-[#e42527] px-5 text-sm font-bold text-white hover:bg-[#c91f21]"><ShoppingCart className="h-4 w-4" />Open POS</Link><Link href="/dashboard/attendance" className="inline-flex h-11 items-center gap-2 rounded-lg border border-slate-300 bg-white px-5 text-sm font-bold text-slate-800 hover:bg-slate-50"><Clock3 className="h-4 w-4" />View attendance</Link></div></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Link href="/dashboard/attendance" className="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-[#ffda32] hover:shadow-sm"><Clock3 className="h-5 w-5 text-[#c91f21]" /><p className="mt-4 text-sm font-medium text-slate-500">Attendance</p><p className="mt-1 text-xl font-bold text-slate-950">{activeClockIn ? 'Clocked in' : 'View attendance'}</p><p className="mt-1 text-sm text-slate-500">{time ? `Since ${time}` : 'Manage your work time'}</p></Link><Link href="/dashboard/pos" className="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-[#ffda32] hover:shadow-sm"><ShoppingCart className="h-5 w-5 text-[#c91f21]" /><p className="mt-4 text-sm font-medium text-slate-500">Point of sale</p><p className="mt-1 text-xl font-bold text-slate-950">Start a sale</p><p className="mt-1 text-sm text-slate-500">Checkout customers and manage your register.</p></Link><Link href="/dashboard/customers" className="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-[#ffda32] hover:shadow-sm"><Users className="h-5 w-5 text-[#c91f21]" /><p className="mt-4 text-sm font-medium text-slate-500">Customers</p><p className="mt-1 text-xl font-bold text-slate-950">Customer directory</p><p className="mt-1 text-sm text-slate-500">Find or add customers for checkout.</p></Link><Link href="/dashboard/pos/history" className="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-[#ffda32] hover:shadow-sm"><ReceiptText className="h-5 w-5 text-[#c91f21]" /><p className="mt-4 text-sm font-medium text-slate-500">Receipts</p><p className="mt-1 text-xl font-bold text-slate-950">Sale history</p><p className="mt-1 text-sm text-slate-500">Find and reprint recent receipts.</p></Link></section></main>
}
