import assert from 'node:assert/strict'
import fs from 'node:fs'
const read=(path:string)=>fs.readFileSync(path,'utf8')
const form=read('components/auth/setup-account-form.tsx'), page=read('app/setup-account/page.tsx'), admin=read('components/staff/staff-management-table.tsx'), reset=read('components/auth/forgot-password-form.tsx')
const signInPage=read('app/sign-in/page.tsx'), authForm=read('components/auth/auth-form.tsx'), activation=read('app/auth/staff-activation/route.ts'), actions=read('app/actions/staff-actions.ts')
for(const copy of ['Create your account','Account email','Confirm password','Sign in and accept invitation','Accept invitation','Check your email','Resend verification email','Resend in','Invitation accepted','Continue to Pesaby','Forgot your password?']) assert.match(form,new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))
assert.doesNotMatch(form,/name="(?:email|role|branch|organization)"/)
assert.match(form,/autoComplete="new-password"/)
assert.match(form,/\/setup-account\?token=\$\{token\}/)
assert.match(actions,/invitationRedirectUrl\(\)}\?token=/)
assert.match(signInPage,/callbackURL\?: string/)
assert.match(signInPage,/safeInternalPath/)
assert.match(authForm,/router\.replace\(callbackURL \|\| '\/auth\/continue'\)/)
assert.match(form,/signedInForInvitation/)
assert.match(form,/forgot-password\?callbackURL=/)
assert.match(reset,/\/reset-password/)
assert.match(reset,/returnTo=\$\{encodeURIComponent\(returnTo\)\}/)
assert.doesNotMatch(reset,/redirectTo: `\$\{window\.location\.origin\}\$\{redirectTo\}`/)
assert.match(activation,/setup-account\?activation=success/)
for(const copy of ['Your account is ready','This invitation has expired','A newer invitation was sent',"This invitation isn't valid",'Account activation unavailable']) assert.match(page,new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))
for(const copy of ['Invitation pending','Awaiting email verification','Invitation expired','Invitation revoked','Send new invitation']) assert.match(admin,new RegExp(copy))
assert.doesNotMatch(admin,/Send password reset/)
console.log('Staff invitation UI contract checks passed')
