import { getNotificationSettings, saveNotificationSettings } from '@/app/actions/notification-settings'

export default async function NotificationsPage() {
  const settings = await getNotificationSettings()
  async function save(form: FormData) { 'use server'; await saveNotificationSettings({ lowStock: form.get('lowStock') === 'on', outOfStock: form.get('outOfStock') === 'on', dailyDigest: form.get('dailyDigest') === 'on', digestTime: String(form.get('digestTime') || '20:00') }) }
  return <main className="mx-auto max-w-3xl space-y-6 p-6"><div><p className="text-sm font-semibold text-red-600">Admin settings</p><h1 className="text-3xl font-bold">Notifications</h1><p className="mt-2 text-sm text-slate-600">Recipients are resolved from current active staff access and roles.</p></div><form action={save} className="space-y-5"><section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Inventory alerts</h2><Setting name="lowStock" title="Low stock" checked={settings.lowStock} recipients="Inventory / Storekeeper, Store Manager"/><Setting name="outOfStock" title="Out of stock" checked={settings.outOfStock} recipients="Inventory / Storekeeper, Store Manager, Owner, Admin"/></section><section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Daily report</h2><Setting name="dailyDigest" title="Daily Business Digest" checked={settings.dailyDigest} recipients="Owner, Admin, and assigned Store Managers"/><label className="mt-4 block text-sm font-medium">Delivery time<input name="digestTime" type="time" defaultValue={settings.digestTime} className="mt-2 block rounded-md border px-3 py-2"/></label><p className="mt-2 text-xs text-slate-500">Time zone: {settings.timezone}</p></section><button className="rounded-md bg-red-600 px-5 py-2.5 font-semibold text-white">Save notification settings</button></form></main>
}

function Setting({ name, title, checked, recipients }: { name: string; title: string; checked: boolean; recipients: string }) { return <label className="mt-4 flex items-start justify-between gap-4 border-t pt-4"><span><strong>{title}</strong><span className="block text-sm text-slate-500">Recipients: {recipients}</span></span><input type="checkbox" name={name} defaultChecked={checked} className="mt-1 h-5 w-5"/></label> }
