'use client'

import { useMemo, useState, useTransition } from 'react'
import { importProductsFromCsv, previewProductImport } from '@/app/actions/product-import'
import { notify } from '@/lib/notify'

const headers = ['name', 'sku', 'barcode', 'category', 'costPrice', 'sellingPrice', 'openingStock', 'ageRestricted']
const optionalHeaders = ['isActive']
const example = ['Jameson 750ML', 'INV00235', '', 'Whisky', '2376.27', '2800', '12', 'true']
type Row = { rowNumber: number; [key: string]: string | number | undefined }

function parseCsv(text: string) { const rows: string[][] = []; let row: string[] = [], cell = '', quoted = false; for (let i = 0; i < text.length; i++) { const char = text[i]; if (char === '"' && quoted && text[i + 1] === '"') { cell += '"'; i++ } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { row.push(cell.trim()); cell = '' } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && text[i + 1] === '\n') i++; row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); row = []; cell = '' } else cell += char }; row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); return rows }

export function ProductCsvImporter({ branches }: { branches: Array<{ id: string; name: string; code: string }> }) {
  const [branchId, setBranchId] = useState(branches[0]?.id ?? ''), [text, setText] = useState(`${headers.join(',')}\n${example.join(',')}`), [preview, setPreview] = useState<Awaited<ReturnType<typeof previewProductImport>> | null>(null), [pending, startTransition] = useTransition()
  const parsed = useMemo(() => { const data = parseCsv(text); if (!data.length) return { rows: [] as Row[], error: 'CSV is empty.' }; const actual = data[0].map((cell) => cell.trim()); const missing = headers.filter((header) => !actual.includes(header)); if (missing.length) return { rows: [] as Row[], error: `Missing columns: ${missing.join(', ')}` }; const index = new Map(actual.map((header, position) => [header, position])); return { rows: data.slice(1, 501).map((cells, offset) => Object.fromEntries([...headers, ...optionalHeaders].map((header) => [header, index.has(header) ? cells[index.get(header)!] || '' : '']).concat([['rowNumber', String(offset + 2)]])) as Row), error: data.length > 501 ? 'Maximum import size is 500 rows.' : undefined } }, [text])
  const request = () => ({ branchId, rows: parsed.rows.map((row) => ({ rowNumber: Number(row.rowNumber), name: String(row.name), sku: String(row.sku), barcode: String(row.barcode), category: String(row.category), costPrice: String(row.costPrice), sellingPrice: String(row.sellingPrice), openingStock: String(row.openingStock), ageRestricted: String(row.ageRestricted), isActive: String(row.isActive || '') })) })
  const previewRows = () => startTransition(async () => { try { if (parsed.error) throw new Error(parsed.error); if (!branchId) throw new Error('Select an inventory branch.'); setPreview(await previewProductImport(request())) } catch (error) { notify.error(error instanceof Error ? error.message : 'Unable to preview this CSV') } })
  const confirm = () => startTransition(async () => { try { const result = await importProductsFromCsv(request()); notify.success(`${result.imported} products imported`); setPreview(null) } catch (error) { notify.error(error instanceof Error ? error.message : 'Import failed', { duration: 10000 }) } })
  return <div className="space-y-4"><section className="rounded-xl border bg-card p-4"><h2 className="text-sm font-semibold">CSV catalogue import</h2><p className="mt-1 text-xs text-muted-foreground">Create-only import. Product codes are SKUs, not barcodes. Maximum 500 rows.</p><div className="mt-4 grid gap-3 sm:grid-cols-[260px_1fr]"><label className="grid gap-1 text-sm font-medium">Inventory branch<select value={branchId} onChange={(event) => { setBranchId(event.target.value); setPreview(null) }} className="h-10 rounded-md border bg-background px-3 text-sm">{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name} ({branch.code})</option>)}</select></label><label className="grid gap-1 text-sm font-medium">CSV file<input type="file" accept=".csv,text/csv" className="text-xs" onChange={async (event) => { const file = event.target.files?.[0]; if (file) { setText(await file.text()); setPreview(null) } }} /></label></div><textarea value={text} onChange={(event) => { setText(event.target.value); setPreview(null) }} rows={12} spellCheck={false} className="mt-4 w-full rounded-lg border bg-background p-3 font-mono text-[11px]" /></section>{parsed.error && <p className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{parsed.error}</p>}<section className="rounded-xl border bg-card p-4 text-sm"><p><b>{parsed.rows.length}</b> rows ready for server-side preview.</p><p className="mt-1 text-xs text-muted-foreground">Required columns: {headers.join(', ')}. Optional: isActive.</p></section>{preview && <section className="rounded-xl border bg-card p-4"><div className="flex gap-5 text-sm"><span><b>{preview.validRows}</b> valid</span><span><b>{preview.invalidRows}</b> invalid</span><span><b>{preview.warnings.length}</b> warnings</span></div>{preview.errors.length > 0 && <div className="mt-3 max-h-56 space-y-1 overflow-auto rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-xs text-destructive">{preview.errors.map((error, index) => <p key={`${error.rowNumber}-${index}`}>Row {error.rowNumber}: {error.message}</p>)}</div>}{preview.warnings.length > 0 && <div className="mt-3 max-h-40 space-y-1 overflow-auto text-xs text-muted-foreground">{preview.warnings.slice(0, 50).map((warning) => <p key={warning}>{warning}</p>)}</div>}</section>}<div className="flex justify-end gap-2"><button disabled={pending || Boolean(parsed.error) || !parsed.rows.length} onClick={previewRows} className="rounded-lg border px-4 py-2.5 text-sm font-semibold disabled:opacity-40">{pending ? 'Checking…' : 'Validate & preview'}</button>{preview && <button disabled={pending || preview.invalidRows > 0 || preview.validRows === 0} onClick={confirm} className="rounded-lg bg-foreground px-4 py-2.5 text-sm font-semibold text-background disabled:opacity-40">Confirm import</button>}</div></div>
}
