'use client'

import { useMemo, useState, useTransition } from 'react'
import { notify } from '@/lib/notify'
import { importPharmacyMedicines } from '@/app/actions/pharmacy-import'

const headers = ['name','genericName','brand','sku','barcode','category','buyingPrice','sellingPrice','minStock','unit','manufacturer','strength','dosageForm','packSize','prescriptionRequired','restrictedItem','branchCode','openingStock','lotNumber','batchBarcode','expiryDate','etimsItemCode','etimsUnitCode','etimsTaxRate']
const example = ['Paracetamol 500mg','Paracetamol','Example Pharma','MED-001','616000000001','Over-the-Counter','20','50','20','tablet','Example Pharma','500mg','tablet','100 tablets','false','false','MAIN','100','PCM-2026-01','BATCH-PCM-2026-01','2027-12-31','','','16']

function parseCsv(text: string) {
  const rows: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false
  for (let index = 0; index < text.length; index++) { const char = text[index]; if (char === '"' && quoted && text[index + 1] === '"') { cell += '"'; index++ } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { row.push(cell.trim()); cell = '' } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && text[index + 1] === '\n') index++; row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); row = []; cell = '' } else cell += char }
  row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); return rows
}

function bool(value: string) { return ['true','yes','1'].includes(value.trim().toLowerCase()) }

export function MedicineImporter({ categories, branches }: { categories: string[]; branches: Array<{ code: string; name: string }> }) {
  const [text, setText] = useState(`${headers.join(',')}\n${example.join(',')}`); const [pending, startTransition] = useTransition()
  const parsed = useMemo(() => { const rows = parseCsv(text); if (!rows.length) return { rows: [], errors: ['CSV is empty'] }; const actual = rows[0].map((item) => item.trim()); const missing = headers.filter((item) => !actual.includes(item)); if (missing.length) return { rows: [], errors: [`Missing columns: ${missing.join(', ')}`] }; const index = new Map(actual.map((name, position) => [name, position])); const values = rows.slice(1).map((cells, offset) => ({ rowNumber: offset + 2, name: cells[index.get('name')!] || '', genericName: cells[index.get('genericName')!] || undefined, brand: cells[index.get('brand')!] || undefined, sku: cells[index.get('sku')!] || '', barcode: cells[index.get('barcode')!] || undefined, category: cells[index.get('category')!] || '', buyingPrice: Number(cells[index.get('buyingPrice')!]), sellingPrice: Number(cells[index.get('sellingPrice')!]), minStock: Number(cells[index.get('minStock')!] || 0), unit: cells[index.get('unit')!] || 'pcs', manufacturer: cells[index.get('manufacturer')!] || undefined, strength: cells[index.get('strength')!] || undefined, dosageForm: cells[index.get('dosageForm')!] || undefined, packSize: cells[index.get('packSize')!] || undefined, prescriptionRequired: bool(cells[index.get('prescriptionRequired')!] || ''), restrictedItem: bool(cells[index.get('restrictedItem')!] || ''), branchCode: cells[index.get('branchCode')!] || undefined, openingStock: Number(cells[index.get('openingStock')!] || 0), lotNumber: cells[index.get('lotNumber')!] || undefined, batchBarcode: cells[index.get('batchBarcode')!] || undefined, expiryDate: cells[index.get('expiryDate')!] || undefined, etimsItemCode: cells[index.get('etimsItemCode')!] || undefined, etimsUnitCode: cells[index.get('etimsUnitCode')!] || undefined, etimsTaxRate: cells[index.get('etimsTaxRate')!] ? Number(cells[index.get('etimsTaxRate')!]) : undefined })); const errors = values.flatMap((row) => { const list: string[] = []; if (!row.name || !row.sku || !row.category) list.push(`Row ${row.rowNumber}: name, SKU and category are required`); if (!Number.isFinite(row.buyingPrice) || !Number.isFinite(row.sellingPrice)) list.push(`Row ${row.rowNumber}: prices are invalid`); if (row.openingStock > 0 && (!row.branchCode || !row.lotNumber || !row.expiryDate)) list.push(`Row ${row.rowNumber}: opening stock requires branch, batch and expiry`); return list }); return { rows: values, errors } }, [text])
  const download = () => { const blob = new Blob([`${headers.join(',')}\n${example.join(',')}\n`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'pesaby-pharmacy-medicine-import.csv'; link.click(); URL.revokeObjectURL(url) }
  return <div className="space-y-4"><section className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">CSV setup</h2><p className="text-xs text-muted-foreground">Preview and validate up to 500 medicines before one transactional import.</p></div><button onClick={download} className="rounded-md border px-3 py-2 text-xs font-semibold hover:bg-muted">Download template</button></div><div className="mt-3 grid gap-2 text-xs text-muted-foreground md:grid-cols-2"><p><b className="text-foreground">Categories:</b> {categories.join(', ') || 'Create a category first'}</p><p><b className="text-foreground">Branches:</b> {branches.map((item) => `${item.code} (${item.name})`).join(', ') || 'Create a branch first'}</p></div><input type="file" accept=".csv,text/csv" className="mt-4 block text-xs" onChange={async (event) => { const file = event.target.files?.[0]; if (file) setText(await file.text()) }} /><textarea value={text} onChange={(event) => setText(event.target.value)} rows={10} spellCheck={false} className="mt-3 w-full rounded-lg border bg-background p-3 font-mono text-[11px]" /></section>
    {parsed.errors.length > 0 && <section className="rounded-xl border border-red-200 bg-red-50/40 p-4 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{parsed.errors.map((error) => <p key={error}>{error}</p>)}</section>}
    <section className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center justify-between border-b p-4"><h2 className="text-sm font-semibold">Preview</h2><span className="text-xs text-muted-foreground">{parsed.rows.length} rows</span></div><div className="max-h-96 overflow-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="sticky top-0 border-b bg-card"><tr>{['Row','Medicine','SKU','Category','Price','Opening stock','Batch / expiry','Flags'].map((item) => <th key={item} className="px-3 py-2">{item}</th>)}</tr></thead><tbody className="divide-y">{parsed.rows.map((row) => <tr key={row.rowNumber}><td className="px-3 py-2">{row.rowNumber}</td><td className="px-3 py-2 font-semibold">{row.name}<p className="font-normal text-muted-foreground">{[row.genericName,row.strength,row.dosageForm].filter(Boolean).join(' · ')}</p></td><td className="px-3 py-2 font-mono">{row.sku}</td><td className="px-3 py-2">{row.category}</td><td className="px-3 py-2">KES {row.sellingPrice}</td><td className="px-3 py-2">{row.openingStock} · {row.branchCode || '—'}</td><td className="px-3 py-2">{row.lotNumber || '—'} · {row.expiryDate || '—'}</td><td className="px-3 py-2">{[row.prescriptionRequired && 'Rx', row.restrictedItem && 'Restricted'].filter(Boolean).join(', ') || 'OTC'}</td></tr>)}</tbody></table></div></section>
    <div className="flex justify-end"><button disabled={pending || parsed.errors.length > 0 || !parsed.rows.length} onClick={() => startTransition(async () => { try { const result = await importPharmacyMedicines(parsed.rows); notify.success(`${result.imported} medicines imported`) } catch (error) { notify.error(error instanceof Error ? error.message : 'Import failed', { duration: 10000 }) } })} className="rounded-lg bg-foreground px-4 py-2.5 text-sm font-semibold text-background disabled:opacity-40">{pending ? 'Importing…' : `Import ${parsed.rows.length} medicines`}</button></div>
  </div>
}
