'use client'
import { useTransition } from 'react'
import { toast } from 'sonner'
import { closePosSession, openPosSession, recordInventoryLoss, refundSale } from '@/app/actions/operations'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import type { PosSession, Product, Sale } from '@/lib/db/schema'

export function OperationsControl({ products, sales, openSession }: { products: Product[]; sales: Sale[]; openSession?: PosSession }) {
 const [pending,start] = useTransition(); const run=(fn:()=>Promise<void>,msg:string)=>start(async()=>{try{await fn();toast.success(msg)}catch(e){toast.error(e instanceof Error?e.message:'Operation failed')}})
 return <div className="grid gap-4 lg:grid-cols-3"><Panel title={openSession?'Close cash register':'Open cash register'}><form action={(f)=>openSession?run(()=>closePosSession(Number(f.get('cash')),String(f.get('notes')||'')),'Register closed and reconciled'):run(()=>openPosSession(Number(f.get('cash'))),'Register opened')} className="space-y-3"><Input name="cash" type="number" min="0" step="0.01" required placeholder={openSession?'Counted closing cash':'Opening float'} />{openSession&&<Input name="notes" placeholder="Closing notes (optional)"/>}<Button disabled={pending} className="w-full">{openSession?'Close and reconcile':'Open register'}</Button></form></Panel><Panel title="Record damaged or lost stock"><form action={(f)=>run(()=>recordInventoryLoss({productId:String(f.get('productId')),quantity:Number(f.get('quantity')),type:String(f.get('type')),reason:String(f.get('reason'))}),'Stock loss recorded')} className="space-y-3"><Choice name="productId" placeholder="Choose product" items={products.map(p=>[p.id,`${p.name} · ${p.stock} available`])}/><Choice name="type" placeholder="Loss type" items={['damaged','expired','lost','theft','count_adjustment'].map(x=>[x,x.replace('_',' ')])}/><Input name="quantity" type="number" min="1" required placeholder="Quantity"/><Input name="reason" minLength={3} required placeholder="Reason or evidence reference"/><Button disabled={pending} className="w-full">Record stock loss</Button></form></Panel><Panel title="Refund a completed sale"><form action={(f)=>run(()=>refundSale({saleId:String(f.get('saleId')),refundMethod:String(f.get('refundMethod')),disposition:String(f.get('disposition')),reason:String(f.get('reason'))}),'Credit note and refund recorded')} className="space-y-3"><Choice name="saleId" placeholder="Choose receipt" items={sales.map(s=>[s.id,`${s.receiptNo} · ${s.total}`])}/><Choice name="refundMethod" placeholder="Refund method" items={['cash','mpesa','card','store_credit'].map(x=>[x,x])}/><Choice name="disposition" placeholder="Returned goods" items={[["restock","Return to stock"],["damaged","Damaged — do not restock"]]}/><Input name="reason" minLength={3} required placeholder="Reason for refund"/><Button disabled={pending} className="w-full bg-[#e42527] text-white hover:bg-[#c91f21]">Issue full refund</Button></form></Panel></div>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border bg-white p-5 dark:bg-card"><h2 className="mb-4 font-bold">{title}</h2>{children}</section>}
function Choice({name,placeholder,items}:{name:string;placeholder:string;items:string[][]}){return <Select name={name}><SelectTrigger><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{items.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
