import Link from 'next/link'
import { and, asc, eq, inArray } from 'drizzle-orm'
import { ReceiptText } from 'lucide-react'
import { db } from '@/lib/db'
import { branch, etimsConfiguration } from '@/lib/db/schema'
import { requireDashboardPermission } from '@/lib/auth/dashboard-access'
import { PermissionEnum } from '@/lib/types/permissions'
import { getEtimsDashboard } from '@/app/actions/etims'
import { EtimsConfigurationPanel } from '@/components/etims/etims-configuration-panel'
import { EtimsCreditRetryButton, EtimsRetryButton } from '@/components/etims/etims-retry-button'
import { DashboardPageHeading } from '@/components/dashboard/page-heading'
import { formatCurrency, formatDateTime } from '@/lib/utils'

export const metadata = { title: 'eTIMS reconciliation | Pesaby' }
export const dynamic = 'force-dynamic'

function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value }

export default async function EtimsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const authorization = await requireDashboardPermission(PermissionEnum.ETIMS_VIEW)
  const params = await searchParams
  const filters = { status: one(params.status), branchId: one(params.branch), receipt: one(params.receipt), from: one(params.from), to: one(params.to) }
  const branchScope = authorization.isOrganizationWide ? undefined : inArray(branch.id, authorization.branchIds.length ? authorization.branchIds : [''])
  const branches = await db.select({ id: branch.id, name: branch.name, code: branch.code }).from(branch).where(and(eq(branch.organizationId, authorization.organizationId), branchScope)).orderBy(asc(branch.name))
  const configurations = authorization.permissions.includes(PermissionEnum.ETIMS_CONFIGURE)
    ? await db.select().from(etimsConfiguration).where(and(eq(etimsConfiguration.organizationId, authorization.organizationId), branchScope ? inArray(etimsConfiguration.branchId, authorization.branchIds) : undefined))
    : []
  const dashboard = await getEtimsDashboard(filters)
  const activity = [
    ['Submitted today', dashboard.summary.submittedToday], ['Accepted', dashboard.summary.accepted], ['Pending', dashboard.summary.pending],
    ['Failed', dashboard.summary.failed], ['Awaiting retry', dashboard.summary.retrying], ['Credit notes', dashboard.summary.creditNotes],
  ]
  return <div className="mx-auto max-w-[1480px] space-y-5 pb-10">
    <DashboardPageHeading icon={ReceiptText} title="eTIMS" description="Configure fiscal invoicing and keep every submission reconciled." theme="adaptive" />
    {authorization.permissions.includes(PermissionEnum.ETIMS_CONFIGURE) && <EtimsConfigurationPanel branches={branches} configurations={configurations.map((item) => ({ ...item, environment: item.environment === 'production' ? 'production' as const : 'sandbox' as const, integrationMethod: item.integrationMethod === 'VSCU' ? 'VSCU' as const : 'OSCU' as const, businessKraPin: item.businessKraPin ?? '', externalBranchId: item.externalBranchId ?? '', deviceId: item.deviceId ?? '', apiBaseUrl: item.apiBaseUrl ?? '', credentialReference: item.credentialReference ?? '', clientId: item.clientId ?? '', clientSecretReference: item.clientSecretReference ?? '', certificateReference: item.certificateReference ?? '', privateKeyReference: item.privateKeyReference ?? '' }))} />}
    <section className="app-panel overflow-hidden">
      <div className="border-b px-5 py-4"><h2 className="text-lg font-semibold leading-tight tracking-tight">Reconciliation overview</h2><p className="mt-1 text-xs text-muted-foreground">A quick view of fiscal delivery and accepted values.</p></div>
      <div className="grid grid-cols-2 divide-x border-b sm:grid-cols-3 lg:grid-cols-6">{activity.map(([label, value]) => <div key={String(label)} className="px-4 py-4"><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1.5 text-xl font-bold tabular-nums">{Number(value)}</p></div>)}</div>
      <div className="grid divide-y sm:grid-cols-3 sm:divide-x sm:divide-y-0"><SummaryValue label="Accepted sales value" value={formatCurrency(Number(dashboard.summary.acceptedValue))} /><SummaryValue label="Accepted tax" value={formatCurrency(Number(dashboard.summary.acceptedTax))} /><SummaryValue label="Credited amount" value={formatCurrency(Number(dashboard.summary.creditedAmount))} /></div>
    </section>
    <section className="app-panel overflow-hidden"><div className="border-b px-4 py-4"><div className="mb-3"><h2 className="text-lg font-semibold leading-tight tracking-tight">Invoice reconciliation</h2><p className="mt-1 text-xs text-muted-foreground">Find submissions, review failures and retry invoices that need attention.</p></div><form className="flex flex-wrap items-end gap-2"><Filter label="Status"><select name="status" defaultValue={filters.status ?? 'all'} className="h-9 rounded-lg border bg-background px-3 text-xs"><option value="all">All statuses</option>{['PENDING','SUBMITTING','ACCEPTED','FAILED','RETRYING','CREDITED'].map((status) => <option key={status}>{status}</option>)}</select></Filter><Filter label="Branch"><select name="branch" defaultValue={filters.branchId ?? ''} className="h-9 rounded-lg border bg-background px-3 text-xs"><option value="">All branches</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Filter><Filter label="Receipt"><input name="receipt" defaultValue={filters.receipt ?? ''} placeholder="Receipt number" className="h-9 rounded-lg border bg-background px-3 text-xs" /></Filter><Filter label="From"><input name="from" type="date" defaultValue={filters.from ?? ''} className="h-9 rounded-lg border bg-background px-3 text-xs" /></Filter><Filter label="To"><input name="to" type="date" defaultValue={filters.to ?? ''} className="h-9 rounded-lg border bg-background px-3 text-xs" /></Filter><button className="h-9 rounded-lg bg-primary px-4 text-xs font-bold text-primary-foreground">Apply filters</button></form></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="border-b bg-muted/30 text-muted-foreground"><tr>{['Receipt','Date / customer','Amount','Tax','Status','eTIMS reference','Attempts','Last error','Last submission','Actions'].map((item) => <th key={item} className="px-4 py-3 font-semibold">{item}</th>)}</tr></thead><tbody className="divide-y">{dashboard.rows.map((row) => <tr key={row.id} className="align-top"><td className="px-4 py-3 font-semibold">{row.receiptNo}</td><td className="px-4 py-3"><p>{formatDateTime(row.createdAt)}</p><p className="mt-1 text-muted-foreground">{row.customerName ?? 'Walk-in'}</p></td><td className="px-4 py-3 font-semibold tabular-nums">{formatCurrency(row.amount)}</td><td className="px-4 py-3 tabular-nums">{formatCurrency(row.tax)}</td><td className="px-4 py-3"><Status value={row.status} /></td><td className="max-w-40 px-4 py-3 font-mono text-[10px]">{row.reference ?? '—'}{row.environment === 'sandbox' && <span className="mt-1 block font-sans font-bold text-amber-700">SANDBOX</span>}</td><td className="px-4 py-3 text-center">{row.attempts}</td><td className="max-w-60 px-4 py-3 text-rose-700">{row.lastError ?? '—'}</td><td className="px-4 py-3">{row.lastSubmissionAt ? formatDateTime(row.lastSubmissionAt) : '—'}</td><td className="px-4 py-3"><div className="flex gap-2"><Link href={`/dashboard/sales/${row.saleId}`} className="inline-flex h-8 items-center rounded-lg border px-2.5 font-semibold">View sale</Link>{authorization.permissions.includes(PermissionEnum.ETIMS_RETRY) && ['FAILED','RETRYING','PENDING'].includes(row.status) && <EtimsRetryButton id={row.id} />}</div>{row.responseData != null && <details className="mt-2"><summary className="cursor-pointer text-[10px] font-semibold text-muted-foreground">Raw response</summary><pre className="mt-1 max-h-40 max-w-80 overflow-auto rounded bg-zinc-950 p-2 text-[9px] text-zinc-100">{JSON.stringify(row.responseData, null, 2)}</pre></details>}</td></tr>)}{!dashboard.rows.length && <tr><td colSpan={10} className="px-4 py-12 text-center text-muted-foreground">No eTIMS submissions match these filters.</td></tr>}</tbody></table></div>
    </section>
    {dashboard.creditRows.length > 0 && <section className="app-panel overflow-hidden"><div className="border-b px-4 py-3"><h2 className="text-lg font-semibold leading-tight tracking-tight">eTIMS credit notes</h2><p className="mt-1 text-xs text-muted-foreground">Fiscal corrections linked to completed returns and their original sale.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><thead className="border-b bg-muted/30"><tr>{['Return','Original receipt','Amount','Status','Reference','Attempts','Last error','Action'].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y">{dashboard.creditRows.map((row) => <tr key={row.id}><td className="px-4 py-3 font-semibold">{row.returnNo}</td><td className="px-4 py-3"><Link className="underline" href={`/dashboard/sales/${row.saleId}`}>{row.receiptNo}</Link></td><td className="px-4 py-3">{formatCurrency(row.amount)}</td><td className="px-4 py-3"><Status value={row.status} /></td><td className="px-4 py-3 font-mono text-[10px]">{row.reference ?? '—'}</td><td className="px-4 py-3">{row.attempts}</td><td className="px-4 py-3 text-rose-700">{row.lastError ?? '—'}</td><td className="px-4 py-3">{authorization.permissions.includes(PermissionEnum.ETIMS_RETRY) && ['FAILED','RETRYING','PENDING'].includes(row.status) && <EtimsCreditRetryButton id={row.id} />}</td></tr>)}</tbody></table></div></section>}
  </div>
}

function Filter({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground"><span>{label}</span>{children}</label> }
function SummaryValue({ label, value }: { label: string; value: string }) { return <div className="px-5 py-4"><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1.5 text-lg font-bold tabular-nums">{value}</p></div> }
function Status({ value }: { value: string }) { const tone = value === 'ACCEPTED' || value === 'CREDITED' ? 'bg-emerald-100 text-emerald-800' : value === 'FAILED' ? 'bg-rose-100 text-rose-800' : 'bg-amber-100 text-amber-800'; return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tone}`}>{value}</span> }
