import { AlertTriangle, ShieldCheck } from 'lucide-react'
import { getMedicineRecalls, getPharmacyBatchInventory } from '@/app/actions/pharmacy'
import { DashboardPageHeading } from '@/components/dashboard/page-heading'
import { ResolveRecallForm, StartRecallForm } from '@/components/pharmacy/recall-actions'
import { formatDateTime } from '@/lib/utils'

export const metadata = { title: 'Medicine recalls | Pesaby' }
export const dynamic = 'force-dynamic'

export default async function MedicineRecallsPage() {
  const [{ recalls, canManage }, inventory] = await Promise.all([getMedicineRecalls(), getPharmacyBatchInventory()])
  const eligible = inventory.batches.filter((batch) => batch.quantity > 0 && !['disposed', 'recalled'].includes(batch.lotStatus))
  return <div className="mx-auto max-w-[1480px] space-y-5 pb-10">
    <DashboardPageHeading icon={AlertTriangle} eyebrow="Pharmacy safety" title="Medicine recalls" description="Block affected batches immediately, trace past sales and record a controlled resolution." theme="adaptive" />
    {canManage && <section className="rounded-xl border bg-card"><div className="border-b px-4 py-3"><h2 className="text-sm font-semibold">Recall a stocked batch</h2><p className="text-xs text-muted-foreground">Starting a recall quarantines the complete remaining batch and removes it from the POS.</p></div><div className="divide-y">{eligible.length ? eligible.map((batch) => <div key={batch.id} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 text-sm"><div><p className="font-semibold">{batch.productName} · {batch.lotNumber}</p><p className="text-xs text-muted-foreground">{batch.branchName} · {batch.quantity} units · expires {batch.expiresAt ? batch.expiresAt.toLocaleDateString('en-KE') : 'missing—review required'}</p></div><StartRecallForm lotId={batch.id} /></div>) : <p className="p-6 text-sm text-muted-foreground">No eligible stocked batches.</p>}</div></section>}
    <section className="rounded-xl border bg-card"><div className="border-b px-4 py-3"><h2 className="text-sm font-semibold">Recall register</h2></div><div className="divide-y">{recalls.length ? recalls.map((record) => <article key={record.id} className="space-y-3 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{record.productName} · batch {record.lotNumber}</p><p className="text-xs text-muted-foreground">{record.reference} · {record.branchName} · {formatDateTime(record.initiatedAt)}</p></div><span className={record.status === 'active' ? 'rounded-full bg-red-50 px-2 py-1 text-xs font-semibold text-red-700 dark:bg-red-950/30 dark:text-red-300' : 'rounded-full border px-2 py-1 text-xs font-semibold'}>{record.status}</span></div><p className="text-sm">{record.reason}</p><div className="flex flex-wrap gap-4 text-xs text-muted-foreground"><span>{record.quantity} remaining units</span><span>{record.affectedSales} affected sale{record.affectedSales === 1 ? '' : 's'}</span></div>{record.affectedReceipts.length > 0 && <details className="rounded-lg border p-3"><summary className="cursor-pointer text-xs font-semibold">Show affected receipts</summary><div className="mt-2 divide-y">{record.affectedReceipts.map((receipt) => <div key={receipt.saleId} className="grid gap-1 py-2 text-xs sm:grid-cols-4"><a href={`/dashboard/sales/${receipt.saleId}`} className="font-mono font-semibold hover:underline">{receipt.receiptNo}</a><span>{receipt.quantity} units</span><span>{receipt.customerName || 'Walk-in'}{receipt.customerPhone ? ` · ${receipt.customerPhone}` : ''}</span><span>{formatDateTime(receipt.soldAt)}</span></div>)}</div></details>}{record.status === 'active' && canManage ? <ResolveRecallForm recallId={record.id} /> : record.resolutionNotes ? <p className="text-xs"><ShieldCheck className="mr-1 inline h-3.5 w-3.5" />{record.resolutionNotes}</p> : null}</article>) : <p className="p-8 text-center text-sm text-muted-foreground">No medicine recalls have been recorded.</p>}</div></section>
  </div>
}
