'use client'

import { useState, useTransition } from 'react'
import { Plus, Truck, UserPlus } from 'lucide-react'
import { toast } from 'sonner'
import { createSupplier, receivePurchase } from '@/app/actions/purchases'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { formatCurrency, formatDateTime } from '@/lib/utils'
import type { Product, Purchase, StockMovement, Supplier } from '@/lib/db/schema'

export function ProcurementManager({ suppliers, purchases, products, movements, currency }: { suppliers: Supplier[]; purchases: Purchase[]; products: Product[]; movements: StockMovement[]; currency: string }) {
  const [supplierOpen, setSupplierOpen] = useState(false)
  const [receiptOpen, setReceiptOpen] = useState(false)
  const [pending, startTransition] = useTransition()
  const run = (work: () => Promise<void>, message: string, close: () => void) => startTransition(async () => { try { await work(); toast.success(message); close() } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not save record') } })
  return <>
    <div className="flex flex-wrap gap-2">
      <Dialog open={supplierOpen} onOpenChange={setSupplierOpen}><DialogTrigger asChild><Button variant="outline" className="gap-2"><UserPlus className="h-4 w-4" />New supplier</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add supplier</DialogTitle></DialogHeader><form action={(form) => run(() => createSupplier({ name: String(form.get('name')), phone: String(form.get('phone') || ''), email: String(form.get('email') || ''), taxId: String(form.get('taxId') || '') }), 'Supplier added', () => setSupplierOpen(false))} className="space-y-4"><Field name="name" label="Supplier name" required /><div className="grid gap-4 sm:grid-cols-2"><Field name="phone" label="Phone" /><Field name="email" label="Email" type="email" /></div><Field name="taxId" label="Tax or registration ID" /><Button disabled={pending} className="w-full">Save supplier</Button></form></DialogContent></Dialog>
      <Dialog open={receiptOpen} onOpenChange={setReceiptOpen}><DialogTrigger asChild><Button disabled={!suppliers.length || !products.length} className="gap-2 bg-[#e42527] font-bold text-white hover:bg-[#c91f21]"><Plus className="h-4 w-4" />Receive stock</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Receive supplier purchase</DialogTitle></DialogHeader><form action={(form) => run(() => receivePurchase({ supplierId: String(form.get('supplierId')), productId: String(form.get('productId')), quantity: Number(form.get('quantity')), unitCost: Number(form.get('unitCost')), paymentStatus: String(form.get('paymentStatus')) as 'unpaid' | 'partial' | 'paid', reference: String(form.get('reference') || ''), notes: String(form.get('notes') || '') }), 'Purchase received and stock updated', () => setReceiptOpen(false))} className="space-y-4"><SelectField name="supplierId" label="Supplier" items={suppliers.map((item) => ({ value: item.id, label: item.name }))} /><SelectField name="productId" label="Product" items={products.map((item) => ({ value: item.id, label: `${item.name} · ${item.stock} ${item.unit} available` }))} /><div className="grid gap-4 sm:grid-cols-2"><Field name="quantity" label="Quantity received" type="number" required min="1" /><Field name="unitCost" label={`Unit cost (${currency})`} type="number" required min="0" step="0.01" /></div><SelectField name="paymentStatus" label="Payment status" defaultValue="unpaid" items={[{value:'unpaid',label:'Unpaid'},{value:'partial',label:'Part paid'},{value:'paid',label:'Paid'}]} /><Field name="reference" label="Supplier invoice/reference" /><Field name="notes" label="Notes" /><Button disabled={pending} className="w-full bg-[#e42527] text-white hover:bg-[#c91f21]">{pending ? 'Receiving…' : 'Receive and update stock'}</Button></form></DialogContent></Dialog>
    </div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.65fr)]"><section className="overflow-hidden rounded-xl border bg-white dark:bg-card"><div className="border-b px-5 py-4"><h2 className="font-bold">Purchase history</h2><p className="mt-1 text-sm text-muted-foreground">Received supplier deliveries and payment status.</p></div>{purchases.length ? <div className="divide-y">{purchases.map((record) => <article key={record.id} className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:px-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#fff3be]"><Truck className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{record.purchaseNo}</p><span className="rounded-full bg-muted px-2 py-0.5 text-xs font-semibold capitalize">{record.paymentStatus}</span></div><p className="mt-1 text-xs text-muted-foreground">{record.supplierName} · {formatDateTime(record.createdAt)}{record.reference ? ` · ${record.reference}` : ''}</p></div><p className="font-extrabold tabular-nums">{formatCurrency(record.total, currency)}</p></article>)}</div> : <div className="flex min-h-56 flex-col items-center justify-center p-8 text-center"><Truck className="h-8 w-8 text-muted-foreground/40" /><p className="mt-3 text-sm font-semibold">No purchases received</p><p className="mt-1 text-sm text-muted-foreground">Add a supplier, then receive stock against a purchase.</p></div>}</section><section className="overflow-hidden rounded-xl border bg-white dark:bg-card"><div className="border-b px-5 py-4"><h2 className="font-bold">Stock movement ledger</h2><p className="mt-1 text-sm text-muted-foreground">Latest auditable stock changes.</p></div>{movements.length ? <div className="divide-y">{movements.map((item) => <div key={item.id} className="px-5 py-3.5"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-bold">{item.productName}</p><span className={item.quantity > 0 ? 'font-bold text-emerald-700' : 'font-bold text-red-600'}>{item.quantity > 0 ? '+' : ''}{item.quantity}</span></div><p className="mt-1 text-xs text-muted-foreground">{item.stockBefore} → {item.stockAfter} · {item.type.replace(/_/g, ' ')} · {formatDateTime(item.createdAt)}</p></div>)}</div> : <div className="p-8 text-center text-sm text-muted-foreground">Stock movements will appear after receiving or selling goods.</div>}</section></div>
  </>
}

function Field({ name, label, ...props }: { name: string; label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} {...props} /></div> }
function SelectField({ name, label, items, defaultValue }: { name: string; label: string; items: {value:string;label:string}[]; defaultValue?: string }) { return <div className="space-y-2"><Label>{label}</Label><Select name={name} defaultValue={defaultValue}><SelectTrigger><SelectValue placeholder={`Choose ${label.toLowerCase()}`} /></SelectTrigger><SelectContent>{items.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div> }
