import { and, eq, inArray } from 'drizzle-orm'
import { db } from '@/lib/db'
import { branch } from '@/lib/db/schema'
import { requireDashboardPermission } from '@/lib/auth/dashboard-access'
import { PermissionEnum, RoleEnum } from '@/lib/types/permissions'
import { getFeedbackReport } from '@/lib/feedback/reporting'

export default async function FeedbackDashboard({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const auth = await requireDashboardPermission(PermissionEnum.REPORT_VIEW); const params = await searchParams
  const allowed = auth.role === RoleEnum.MANAGER ? auth.branchIds : undefined
  const branches = await db.select({ id: branch.id, name: branch.name }).from(branch).where(and(eq(branch.organizationId, auth.organizationId), allowed?.length ? inArray(branch.id, allowed) : undefined))
  const selected = params.branch && branches.some(item => item.id === params.branch) ? [params.branch] : undefined
  const report = await getFeedbackReport({ organizationId: auth.organizationId, branchIds: selected ?? allowed, category: params.category, score: params.score ? Number(params.score) : undefined, tag: params.tag })
  return <main className="mx-auto max-w-6xl space-y-6 p-6"><header><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Insights & reports</p><h1 className="mt-1 text-2xl font-bold">Customer feedback</h1></header><div className="grid gap-3 sm:grid-cols-5">{[['NPS', report.nps > 0 ? `+${report.nps}` : report.nps], ['Responses', report.responses], ['Promoters', report.promoters], ['Passives', report.passives], ['Detractors', report.detractors]].map(([label, value]) => <section key={String(label)} className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></section>)}</div><form className="flex flex-wrap gap-2 rounded-xl border p-3"><select name="branch" defaultValue={params.branch}><option value="">All branches</option>{branches.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="category" defaultValue={params.category}><option value="">All categories</option><option value="PROMOTER">Promoter</option><option value="PASSIVE">Passive</option><option value="DETRACTOR">Detractor</option></select><input name="score" type="number" min="0" max="10" defaultValue={params.score} placeholder="Score" /><button className="rounded-md bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground">Filter</button></form><section className="overflow-hidden rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted/50"><tr>{['Date', 'Branch', 'Score', 'Category', 'Tags', 'Comment'].map(label => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{report.rows.map((row, index) => <tr key={index} className="border-t"><td className="px-4 py-3">{row.submittedAt.toLocaleDateString('en-KE')}</td><td className="px-4 py-3">{row.branchName}</td><td className="px-4 py-3">{row.score}</td><td className="px-4 py-3">{row.category}</td><td className="px-4 py-3">{Array.isArray(row.tags) ? row.tags.join(', ') : ''}</td><td className="px-4 py-3">{row.comment}</td></tr>)}{!report.rows.length && <tr><td colSpan={6} className="px-4 py-10 text-center text-muted-foreground">No feedback for these filters.</td></tr>}</tbody></table></section></main>
}
