'use client'
import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { Eye, EyeOff, MailCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { acceptStaffInvitationAction, resendStaffVerificationAction } from '@/app/actions/staff-invitation-actions'

export function SetupAccountForm({ token, existingAccount, signedInForInvitation, awaitingVerification, invalid, email, businessName }: { token?: string; existingAccount?: boolean; signedInForInvitation?: boolean; awaitingVerification?: boolean; invalid?: boolean; email?: string; businessName?: string }) {
 const router=useRouter(); const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState(''),[cooldown,setCooldown]=useState(0)
 if(invalid||!token)return null
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(password!==confirm)return setMessage('Passwords do not match.');setPending(true);setMessage('');try{const r=await acceptStaffInvitationAction(token,existingAccount?undefined:password);if('awaitingEmailVerification'in r)router.refresh();else router.replace('/dashboard')}catch{setMessage(existingAccount?'This invitation belongs to another account. Sign out and continue using the invited email address.':'We could not create your account. Please try again.')}finally{setPending(false)}}
 const resend=async()=>{setPending(true);setMessage('');try{await resendStaffVerificationAction(token);setMessage('A new verification email has been sent.');setCooldown(30);const id=window.setInterval(()=>setCooldown(v=>{if(v<=1){window.clearInterval(id);return 0}return v-1}),1000)}catch{setMessage('Unable to resend the verification email.')}finally{setPending(false)}}
 if(awaitingVerification)return <div className="space-y-5 text-center"><MailCheck className="mx-auto h-10 w-10 text-amber-500" aria-hidden="true"/><div><h2 className="text-xl font-bold">Check your email</h2><p className="mt-2 text-sm text-muted-foreground">We sent a verification link to {email}. Verify your email to finish activating your employee account.</p></div><Button type="button" variant="outline" className="w-full" disabled={pending||cooldown>0} onClick={resend}>{pending?'Sending…':cooldown?`Resend in ${cooldown}s`:'Resend verification email'}</Button><Link className="block text-sm underline" href="/sign-in">Back to sign in</Link><p className="text-xs text-muted-foreground">Didn’t receive it? Check your spam or junk folder.</p>{message&&<p role="status" className="text-sm">{message}</p>}</div>
 if(existingAccount)return <div className="space-y-5"><h2 className="text-xl font-bold">You’re joining {businessName}</h2><p className="text-sm text-muted-foreground">This invitation is linked to your existing Pesaby account.</p>{email&&<div className="rounded-lg border bg-muted/30 p-3 text-sm"><span className="block text-xs text-muted-foreground">Account email</span>{email}</div>}{signedInForInvitation?<form onSubmit={submit}><Button className="w-full" disabled={pending}>{pending?'Accepting invitation…':'Accept invitation'}</Button></form>:<Button asChild className="w-full"><Link href={`/sign-in?callbackURL=${encodeURIComponent(`/setup-account?token=${token}`)}`}>Sign in to continue</Link></Button>}</div>
 return <form onSubmit={submit} className="space-y-4"><div><h2 className="text-xl font-bold">Create your account</h2><p className="mt-1 text-sm text-muted-foreground">Choose a password you’ll use to sign in to Pesaby.</p></div>{email&&<div className="rounded-lg border bg-muted/30 p-3 text-sm"><span className="block text-xs text-muted-foreground">Account email</span>{email}</div>}<label className="block text-sm font-medium" htmlFor="invite-password">Password<div className="relative mt-1"><Input id="invite-password" type={show?'text':'password'} minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="absolute right-3 top-2.5" type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label><label className="block text-sm font-medium" htmlFor="invite-confirm">Confirm password<Input id="invite-confirm" className="mt-1" type={show?'text':'password'} minLength={8} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{message&&<p role="alert" className="text-sm text-destructive">{message}</p>}<Button className="w-full" disabled={pending}>{pending?'Creating account…':'Create account'}</Button></form>
}
