const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]!);

export function emailVerificationEmail(input: { name?: string | null; email: string; verificationUrl: string }) {
  const name = escapeHtml(input.name?.trim() || 'there');
  const email = escapeHtml(input.email);
  const url = escapeHtml(input.verificationUrl);

  return {
    subject: 'Verify your email to finish setting up Pesaby',
    text: `Hello ${input.name?.trim() || 'there'},\n\nConfirm ${input.email} to finish setting up your Pesaby account:\n${input.verificationUrl}\n\nThis link expires in one hour. If you did not create this account, you can ignore this email.`,
    html: `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Verify your email</title></head><body style="margin:0;background:#f4f6f8;color:#0f172a;font-family:Arial,'Helvetica Neue',sans-serif;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;">Confirm your email to finish setting up Pesaby.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="width:100%;background:#f4f6f8;"><tr><td align="center" style="padding:32px 16px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="width:100%;max-width:520px;"><tr><td style="padding:0 4px 18px;"><table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="width:34px;height:34px;border-radius:9px;background:#ffda32;color:#111827;text-align:center;font-size:20px;font-weight:800;line-height:34px;">P</td><td style="padding-left:10px;color:#0f172a;font-size:18px;font-weight:800;">Pesaby</td></tr></table></td></tr><tr><td style="border:1px solid #e2e8f0;border-radius:16px;background:#ffffff;overflow:hidden;"><div style="height:4px;background:#ffda32;"></div><div style="padding:32px;"><p style="margin:0 0 12px;color:#c91f21;font-size:11px;font-weight:800;letter-spacing:1.1px;text-transform:uppercase;">Account verification</p><h1 style="margin:0 0 14px;color:#0f172a;font-size:26px;line-height:32px;font-weight:800;letter-spacing:-.4px;">Confirm your email</h1><p style="margin:0 0 12px;color:#475569;font-size:15px;line-height:23px;">Hi ${name},</p><p style="margin:0;color:#475569;font-size:15px;line-height:23px;">Use the button below to confirm <strong style="color:#0f172a;">${email}</strong> and finish setting up your account.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:26px 0 22px;"><tr><td align="center" style="border-radius:8px;background:#e42527;"><a href="${url}" style="display:block;padding:13px 20px;color:#ffffff;font-size:15px;font-weight:700;line-height:20px;text-align:center;text-decoration:none;">Verify email address</a></td></tr></table><p style="margin:0;padding:13px 14px;border-radius:8px;background:#f8fafc;color:#64748b;font-size:13px;line-height:20px;">This secure link expires in <strong style="color:#334155;">one hour</strong>. If you did not create this account, you can safely ignore this email.</p><p style="margin:22px 0 0;color:#94a3b8;font-size:12px;line-height:18px;">Having trouble with the button? <a href="${url}" style="color:#c91f21;text-decoration:underline;">Open the verification link</a>.</p></div></td></tr><tr><td style="padding:18px 4px 0;color:#94a3b8;font-size:12px;line-height:18px;text-align:center;">Pesaby · Business made simpler</td></tr></table></td></tr></table></body></html>`,
  };
}
