const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]!)

export function staffInvitationEmail(input: { employeeName: string; organizationName: string; branchName: string; role: string; inviterName: string; setupUrl: string; expiresAt?: Date; department?: string | null }) {
  const name = escapeHtml(input.employeeName), business = escapeHtml(input.organizationName), location = escapeHtml(input.branchName), role = escapeHtml(input.role), inviter = escapeHtml(input.inviterName), url = escapeHtml(input.setupUrl)
  const expiry = input.expiresAt ? new Intl.DateTimeFormat('en-KE', { dateStyle: 'medium', timeStyle: 'short' }).format(input.expiresAt) : 'the time shown in your invitation'
  const department = input.department?.trim()
  const rows = `<tr><td>EMPLOYEE</td><td align="right"><strong>${name}</strong></td></tr><tr><td>ROLE</td><td align="right"><strong>${role}</strong></td></tr><tr><td>LOCATION</td><td align="right"><strong>${location}</strong></td></tr>${department ? `<tr><td>DEPARTMENT</td><td align="right"><strong>${escapeHtml(department)}</strong></td></tr>` : ''}`
  return { subject: `You're invited to join ${input.organizationName} on Pesaby`, text: `Pesaby employee invitation\n\n${input.inviterName} has invited you to access ${input.organizationName} on Pesaby.\n\nEmployee: ${input.employeeName}\nRole: ${input.role}\nLocation: ${input.branchName}${department ? `\nDepartment: ${department}` : ''}\n\nSet up your account: ${input.setupUrl}\n\nThis invitation expires on ${expiry}. If you weren't expecting this invitation, you can safely ignore this email.\n\nPesaby\nSecure business management`, html: `<!doctype html><html><body style="margin:0;background:#f6f7f9;font-family:'Inter','Segoe UI',Arial,sans-serif;color:#111827"><div style="display:none;max-height:0;overflow:hidden">Set up your employee account to get started.</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;background:#fff;border:1px solid #e5e7eb"><tr><td style="padding:28px 32px 16px;border-bottom:3px solid #f4bd23"><strong style="font-size:22px">Pesaby</strong><div style="margin-top:6px;color:#697386;font-size:11px;font-weight:700;letter-spacing:.12em">EMPLOYEE INVITATION</div></td></tr><tr><td style="padding:28px 30px"><h1 style="margin:0 0 16px;font-size:23px;line-height:30px;letter-spacing:-.01em">You're invited to join ${business}</h1><p style="color:#4b5563;font-size:14px;line-height:21px">${inviter} has invited you to access ${business} on Pesaby.</p><table role="presentation" width="100%" cellpadding="10" cellspacing="0" style="border:1px solid #e5e7eb;background:#fafafa;color:#4b5563;font-size:11px;font-weight:600;letter-spacing:.05em">${rows}</table><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:28px"><tr><td align="center" style="background:#f4bd23"><a href="${url}" style="display:block;padding:13px 18px;color:#111827;font-size:14px;font-weight:700;letter-spacing:.01em;text-decoration:none">Set up your account</a></td></tr></table><p style="color:#4b5563;font-size:14px;line-height:21px">Create your password and activate your employee account using this secure invitation.</p><p style="color:#4b5563;font-size:13px">This invitation expires on ${escapeHtml(expiry)}.</p><p style="color:#697386;font-size:13px">If you weren't expecting this invitation, you can safely ignore this email.</p></td></tr><tr><td style="padding:20px;border-top:1px solid #e5e7eb;color:#697386;font-size:12px;text-align:center">Pesaby<br>Secure business management</td></tr></table></td></tr></table></body></html>` }
}
