import Link from 'next/link'
import { Scale } from 'lucide-react'
import { getPharmacyInventoryReconciliation } from '@/app/actions/pharmacy'
import { DashboardPageHeading } from '@/components/dashboard/page-heading'

export const metadata = { title: 'Pharmacy stock reconciliation | Pesaby' }
export const dynamic = 'force-dynamic'

export default async function PharmacyReconciliationPage() { const rows = await getPharmacyInventoryReconciliation(); const issues = rows.filter((row) => !row.healthy); return <div className="mx-auto max-w-[1280px] space-y-5 pb-10"><DashboardPageHeading icon={Scale} eyebrow="Pharmacy inventory" title="Batch reconciliation" description="Compare branch stock balances with the sum and availability state of their medicine batches." theme="adaptive" /><div className="grid gap-3 sm:grid-cols-3"><Metric label="Medicine balances" value={rows.length} /><Metric label="Healthy" value={rows.length - issues.length} /><Metric label="Needs review" value={issues.length} /></div><section className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center justify-between border-b p-4"><div><h2 className="text-sm font-semibold">Reconciliation results</h2><p className="text-xs text-muted-foreground">No stock is changed automatically.</p></div><Link href="/dashboard/inventory?tab=counts" className="rounded-md border px-3 py-2 text-xs font-semibold hover:bg-muted">Start stock count</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b bg-muted/30"><tr>{['Medicine','Branch','Balance','Batch total','Unavailable','Unavailable batches','Missing expiry','Result'].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={`${row.productId}-${row.branchId}`}><td className="px-4 py-3 font-semibold">{row.productName}</td><td className="px-4 py-3">{row.branchName}</td><td className="px-4 py-3">{row.onHand}</td><td className="px-4 py-3">{row.lotTotal}</td><td className="px-4 py-3">{row.unavailable}</td><td className="px-4 py-3">{row.unavailableLotTotal}</td><td className="px-4 py-3">{row.missingExpiry}</td><td className={row.healthy ? 'px-4 py-3 font-semibold text-emerald-700' : 'px-4 py-3 font-semibold text-red-700'}>{row.healthy ? 'Balanced' : `Review (${row.quantityVariance} stock, ${row.unavailableVariance} unavailable)`}</td></tr>)}{!rows.length && <tr><td colSpan={8} className="p-10 text-center text-muted-foreground">No medicine inventory balances yet.</td></tr>}</tbody></table></div></section></div> }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div> }
